"""Post-experiment analysis of one run, one case at a time.

A run (runs/<RUN_ID>/) is one execution of a generated launcher. Each
workload invocation inside it is a case with its own raw Darshan logs:
darshan_logs/run/ without a sweep, darshan_logs/workers_<N>/ per
sweep.num_workers value. Every case gets one complete post-production round:

    raw *.darshan --check--> checks/ --to_json--> json/ --simplify--> simplified.json
                  --selected metrics--> <metric>/ (CSVs and optional graphs)

All derived data goes under analysis/<case>/, which is recreated on each
round; darshan_logs/ is raw evidence and is never modified. Cases are
independent: a failed case stops its own round only, and the command fails
at the end if any case failed.

The run's config.yaml snapshot, never the live campaign.yaml, decides the
cases and which metrics and graph modes are enabled; CLI options can only
select a subset of those. This module is an orchestrator: Darshan counters,
metric formulas, CSVs and graphs belong to the darshanflow.post modules,
which run as subprocesses.
"""

import importlib.util
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

from darshanflow import DarshanFlowError
from darshanflow.campaign import require_campaign
from darshanflow.config import ANALYSIS_GRAPHS, ANALYSIS_METRICS, load_config_file

RUNS_DIR = "runs"
RUN_CONFIG = "config.yaml"
RUN_LAUNCHER = "launcher.sh"
DARSHAN_LOGS_DIR = "darshan_logs"
ANALYSIS_DIR = "analysis"

# Public metric names, in canonical execution order, and their modules.
METRICS = ANALYSIS_METRICS
METRIC_MODULES = {
    "io": "darshanflow.post.io_intensity",
    "access": "darshanflow.post.access_pattern",
    "metadata": "darshanflow.post.metadata_pressure",
    "bandwidth": "darshanflow.post.effective_read",
    "balance": "darshanflow.post.worker_balance",
}
SIMPLIFY_MODULE = "darshanflow.post.simplify_logs"
# CLI graph vocabulary; the run config stores only ANALYSIS_GRAPHS.
GRAPH_MODES = ("none", "compact", "individual", "all")

# Run IDs generated by launchers: <workflow>_YYYYMMDD_HHMMSS.
_RUN_ID = re.compile(r"^.+_(\d{8}_\d{6})$")
INCOMPLETE_MARKER = b"module contains incomplete data"


class _CaseFailed(Exception):
    """A post-production stage failed for one case; other cases continue."""


def analyze_campaign(
    path: str | Path = ".",
    run: str = "latest",
    metrics: list[str] | None = None,
    graphs: str | None = None,
) -> None:
    """Run the post-production pipeline on every case of one run.

    `metrics` and `graphs` are None when not given on the command line: the
    run's config.yaml then decides. Raises DarshanFlowError if the run cannot
    be analyzed or if any case fails.
    """
    root = require_campaign(path)
    run_dir = _resolve_run(root, run)
    config = load_config_file(run_dir / RUN_CONFIG, root)
    if not config["darshan"]["enabled"]:
        raise DarshanFlowError(
            f"run {run_dir.name} was created with Darshan disabled; "
            "there are no Darshan logs to analyze"
        )
    selected_metrics = _select_metrics(config, metrics)
    selected_graphs = _select_graphs(config, graphs)
    cases = _case_logs(run_dir, config)
    if importlib.util.find_spec("darshan") is None:
        raise DarshanFlowError(
            f"the Python 'darshan' module is not available to {sys.executable}; "
            "it is required to convert Darshan logs to JSON"
        )
    include = simplify_include_pattern(config["workload"]["script"], config["dataset"]["path"])

    print(f"Analyzing run: {run_dir.name}")
    print(f"Cases: {len(cases)} ({', '.join(cases)})")
    print(f"Metrics: {', '.join(selected_metrics) or 'none'}")
    print(f"Graphs: {', '.join(selected_graphs) or 'none'}")
    if "io" in selected_metrics and "compact" in selected_graphs:
        print("Note: io_intensity has no compact graphs; it draws graphs only in individual mode.")

    failures = {}
    for case, logs in cases.items():
        print(f"\n[{case}]", flush=True)
        try:
            _analyze_case(run_dir, case, logs, include, selected_metrics, selected_graphs)
            print("  OK")
        except _CaseFailed as exc:
            failures[case] = str(exc)
            print(f"  FAILED: {exc}")

    print(f"\nAnalysis finished for run {run_dir.name}:")
    print(f"  {len(cases) - len(failures)} case(s) succeeded")
    print(f"  {len(failures)} case(s) failed")
    for case, reason in failures.items():
        print(f"    {case}: {reason.splitlines()[0]}")
    print(f"Output: {run_dir / ANALYSIS_DIR}")
    if failures:
        raise DarshanFlowError(
            f"analysis failed for {len(failures)} of {len(cases)} case(s): {', '.join(failures)}"
        )


def simplify_include_pattern(script: Path, dataset: Path) -> str:
    """Return the simplify_logs --include regex keeping workload and dataset records.

    Darshan record names are full paths. For each configured path, match its
    exact normalized path, and its basename (or the legacy `_N` variant
    before the suffix, e.g. train_1.py, dataset_1.h5) as a final path
    component. For the dataset, files under the configured path (a dataset
    directory) match as well. Paths need not exist any more.
    """
    alternatives = []
    for path, descendants in ((script, False), (dataset, True)):
        exact = re.escape(str(path))
        alternatives.append(f"^{exact}(?:/.*)?$" if descendants else f"^{exact}$")
        alternatives.append(f"(?:^|/){re.escape(path.stem)}(?:_[0-9]+)?{re.escape(path.suffix)}$")
    return "|".join(alternatives)


# ---------------------------------------------------------------------------
# Run, cases and selection
# ---------------------------------------------------------------------------

def _resolve_run(root: Path, run: str) -> Path:
    """Return the run directory for `run`, a run ID or "latest".

    "latest" is the newest launcher-generated run by the timestamp in its
    ID, never by directory mtime (analysis itself changes mtimes).
    """
    runs = root / RUNS_DIR
    if run == "latest":
        candidates = [
            (match[1], path.name) for path in (runs.iterdir() if runs.is_dir() else [])
            if (match := _RUN_ID.match(path.name)) and path.is_dir()
            and (path / RUN_CONFIG).is_file() and (path / RUN_LAUNCHER).is_file()
        ]
        if not candidates:
            raise DarshanFlowError(
                f"no runs found in {runs} "
                f"(expected <workflow>_YYYYMMDD_HHMMSS directories with {RUN_CONFIG} and {RUN_LAUNCHER})"
            )
        return runs / max(candidates)[1]

    run_dir = runs / run
    # Reject IDs that escape runs/ (e.g. "..", "a/b") as well as missing runs.
    if run_dir.resolve().parent != runs.resolve() or not run_dir.is_dir():
        raise DarshanFlowError(f"unknown run ID: {run}")
    if not (run_dir / RUN_CONFIG).is_file():
        raise DarshanFlowError(f"run {run} has no {RUN_CONFIG} snapshot; it cannot be analyzed")
    return run_dir


def _case_logs(run_dir: Path, config: dict) -> dict[str, list[Path]]:
    """Return the raw Darshan logs of every case expected by the run config.

    Cases come from the config, not from whatever directories exist: "run"
    without a sweep, "workers_<N>" per sweep.num_workers value. Every case
    must hold at least one direct *.darshan log.
    """
    sweep = config["sweep"]
    names = [f"workers_{n}" for n in sweep["num_workers"]] if sweep else ["run"]
    cases, problems = {}, []
    for name in names:
        case_dir = run_dir / DARSHAN_LOGS_DIR / name
        logs = sorted(p for p in case_dir.glob("*.darshan") if p.is_file()) if case_dir.is_dir() else []
        if not case_dir.is_dir():
            problems.append(f"{DARSHAN_LOGS_DIR}/{name}/ is missing")
        elif not logs:
            problems.append(f"{DARSHAN_LOGS_DIR}/{name}/ contains no .darshan logs")
        cases[name] = logs
    if problems:
        raise DarshanFlowError(
            f"run {run_dir.name} is not ready for analysis (incomplete or still running):\n  "
            + "\n  ".join(problems)
        )
    return cases


def _select_metrics(config: dict, requested: list[str] | None) -> list[str]:
    """Return the metrics to run: the run's enabled metrics, or a subset of them."""
    enabled = [m for m in METRICS if config["analysis"]["metrics"][m]["enabled"]]
    if requested is None or requested == ["all"]:
        return enabled
    if "all" in requested:
        raise DarshanFlowError("--metrics all cannot be combined with explicit metric names")
    unknown = sorted(set(requested) - set(METRICS))
    if unknown:
        raise DarshanFlowError(f"unknown metrics: {', '.join(unknown)}")
    disabled = [m for m in METRICS if m in requested and m not in enabled]
    if disabled:
        raise DarshanFlowError(
            f"metrics disabled in this run's {RUN_CONFIG}: {', '.join(disabled)}"
        )
    return [m for m in METRICS if m in requested]


def _select_graphs(config: dict, requested: str | None) -> list[str]:
    """Return the graph modes to draw: the run's enabled modes, none, or one of them."""
    enabled = [g for g in ANALYSIS_GRAPHS if config["analysis"]["graphs"][g]["enabled"]]
    if requested is None or requested == "all":
        return enabled
    if requested == "none":
        return []
    if requested not in ANALYSIS_GRAPHS:
        raise DarshanFlowError(f"invalid graphs mode: {requested}")
    if requested not in enabled:
        raise DarshanFlowError(f"{requested} graphs are disabled in this run's {RUN_CONFIG}")
    return [requested]


# ---------------------------------------------------------------------------
# One post-production round
# ---------------------------------------------------------------------------

def _analyze_case(run_dir: Path, case: str, logs: list[Path], include: str,
                  metrics: list[str], graphs: list[str]) -> None:
    """Run check -> JSON -> simplify -> metrics for one case; raise _CaseFailed on failure."""
    out = run_dir / ANALYSIS_DIR / case
    # Recreate only this derived directory so no stale output survives.
    if out.exists():
        shutil.rmtree(out)
    (out / "checks").mkdir(parents=True)
    (out / "json").mkdir()

    print(f"  Checking {len(logs)} Darshan logs...", flush=True)
    incomplete, errors = [], []
    for log in logs:
        with open(out / "checks" / f"{log.name}.txt", "wb") as report:
            result = _run(case, "completeness check", ["darshan-parser", "--show-incomplete", str(log)],
                          out, stdout=report, stderr=subprocess.PIPE)
        if result.returncode != 0:
            errors.append(f"darshan-parser exited with code {result.returncode} for "
                          f"{log.name}{_last_line(result.stderr)}")
        elif (INCOMPLETE_MARKER in (out / "checks" / f"{log.name}.txt").read_bytes()
              or INCOMPLETE_MARKER in result.stderr):
            incomplete.append(log.name)
    if errors or incomplete:
        details = errors + [f"INCOMPLETE - {name}" for name in incomplete]
        raise _CaseFailed(
            f"completeness check failed ({len(incomplete)} incomplete, {len(errors)} errors); "
            f"see {ANALYSIS_DIR}/{case}/checks/\n      " + "\n      ".join(details)
        )
    print(f"  {len(logs)}/{len(logs)} complete")

    print("  Converting to JSON...", flush=True)
    for log in logs:
        target = out / "json" / f"{log.name}.json"
        with open(target, "wb") as stream:
            result = _run(case, "JSON conversion", [sys.executable, "-m", "darshan", "to_json", str(log)],
                          out, stdout=stream, stderr=subprocess.PIPE)
        if result.returncode != 0:
            target.unlink()
            raise _CaseFailed(f"JSON conversion of {log.name} failed with exit code "
                              f"{result.returncode}{_last_line(result.stderr)}")

    print("  Simplifying...", flush=True)
    simplified = out / "simplified.json"
    _run_checked(case, "simplify", [sys.executable, "-m", SIMPLIFY_MODULE, str(out / "json"),
                                    "--include", include, "--output", str(simplified)], out)
    # One simplified.json must hold every process log of the invocation;
    # simplify_logs only warns about logs it cannot read.
    try:
        doc = json.loads(simplified.read_text())
        n_logs = doc["n_logs"]
        simplified_logs = doc["logs"]
    except (OSError, ValueError, KeyError, TypeError) as exc:
        raise _CaseFailed(
            f"simplify produced no usable {simplified.name}: {exc}"
        ) from None

    if n_logs != len(logs):
        raise _CaseFailed(
            f"simplify read only {n_logs} of {len(logs)} JSON logs"
        )

    n_records_kept = sum(
        log.get("n_records_kept", 0)
        for log in simplified_logs
    )

    if n_records_kept == 0:
        raise _CaseFailed(
            "simplify filter matched no POSIX records for the configured "
            "workload or dataset"
        )

    for metric in metrics:
        print(f"  Running {metric}...", flush=True)
        command = [sys.executable, "-m", METRIC_MODULES[metric], str(simplified),
                   "--outdir", str(out / metric), *_graph_arguments(metric, graphs)]
        _run_checked(case, metric, command, out)


def _graph_arguments(metric: str, graphs: list[str]) -> list[str]:
    """Translate the selected graph modes into the metric module's graph options.

    io_intensity has a single --graphs switch drawing its file/process/run
    graph set, which corresponds to individual graphs; compact alone does not
    enable it. The other modules take both modes directly.
    """
    def flag(enabled: bool) -> str:
        return "true" if enabled else "false"

    if metric == "io":
        return ["--graphs", flag("individual" in graphs)]
    return ["--compact-graphs", flag("compact" in graphs),
            "--individual-graphs", flag("individual" in graphs)]


def _run(case: str, stage: str, command: list[str], cwd: Path, **streams) -> subprocess.CompletedProcess:
    """Run one stage; a missing program aborts the whole analysis."""
    try:
        return subprocess.run(command, cwd=cwd, env=_child_environment(), **streams)
    except FileNotFoundError:
        raise DarshanFlowError(f"[{case}] {stage}: {command[0]} was not found") from None
    except OSError as exc:
        raise DarshanFlowError(f"[{case}] {stage}: cannot run {command[0]}: {exc.strerror}") from None


def _run_checked(case: str, stage: str, command: list[str], cwd: Path) -> None:
    """Run a stage whose output stays visible; a non-zero exit fails the case."""
    result = _run(case, stage, command, cwd)
    if result.returncode != 0:
        raise _CaseFailed(f"{stage} failed with exit code {result.returncode}: {shlex.join(command)}")


def _child_environment() -> dict[str, str]:
    """Environment for subprocesses: darshanflow.post importable from any directory."""
    package_parent = str(Path(__file__).resolve().parent.parent)
    env = dict(os.environ)
    env["PYTHONPATH"] = os.pathsep.join(filter(None, [package_parent, env.get("PYTHONPATH")]))
    return env


def _last_line(stderr: bytes) -> str:
    lines = stderr.decode(errors="replace").strip().splitlines()
    return f": {lines[-1]}" if lines else ""
